# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6fcd4db9cdacbc44722970b9439b543e8a38b9b0532c4b29d5a47b0cad1dd66d87cf785df85b7b674122826e93125ab96a99f35a7c44ee2a8297a8edccf9f387

test:
  secret_key_base: 0566d8b521e37ec0b9d9e3137bbbb96322b22d5821d6bea3d77702d779befbca872d9705addf03d9b714e56dd5ba6717e551c68a288654869e3d5bef2471714c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
